# Generated by Django 3.0 on 2024-04-10 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='signup',
            fields=[
                ('userid', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=150)),
                ('dob', models.DateField(null=True)),
                ('registerdate', models.DateTimeField(auto_now=True)),
                ('password', models.CharField(max_length=128)),
            ],
        ),
    ]
