# Generated by Django 3.0 on 2024-04-13 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('language', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='login',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('time', models.DateTimeField(auto_now=True)),
                ('aspect', models.CharField(max_length=10)),
            ],
        ),
    ]
