# Generated by Django 3.2.25 on 2024-04-14 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('language', '0002_login'),
    ]

    operations = [
        migrations.AlterField(
            model_name='login',
            name='aspect',
            field=models.CharField(default='login', max_length=10),
        ),
    ]
