# Generated by Django 3.2.25 on 2024-04-27 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('language', '0003_alter_login_aspect'),
    ]

    operations = [
        migrations.CreateModel(
            name='transalate',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=200)),
                ('fromlang', models.TextField()),
                ('tolang', models.TextField()),
                ('fromtext', models.TextField()),
                ('totext', models.TextField()),
                ('date', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
