# Generated by Django 3.2.25 on 2024-05-01 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('language', '0004_transalate'),
    ]

    operations = [
        migrations.CreateModel(
            name='translation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fromlang', models.CharField(max_length=200)),
                ('tolang', models.TextField()),
                ('fromtext', models.TextField()),
                ('totext', models.TextField()),
                ('date', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
