# Generated by Django 3.1.3 on 2024-05-03 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('language', '0006_feedback'),
    ]

    operations = [
        migrations.CreateModel(
            name='feedbackt',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=10)),
                ('date', models.DateTimeField(auto_now=True)),
                ('query', models.TextField()),
                ('comment', models.TextField()),
                ('rating', models.IntegerField()),
            ],
        ),
    ]
