# Generated by Django 3.1.3 on 2024-05-03 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('language', '0007_feedbackt'),
    ]

    operations = [
        migrations.CreateModel(
            name='audio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audioname', models.CharField(max_length=100)),
                ('audio', models.FileField(upload_to='audio')),
            ],
        ),
    ]
