# Generated by Django 3.1.3 on 2024-05-04 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('language', '0008_audio'),
    ]

    operations = [
        migrations.CreateModel(
            name='quotes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
                ('text', models.TextField()),
            ],
        ),
    ]
