# Generated by Django 3.1.3 on 2024-05-05 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('language', '0010_quotesg'),
    ]

    operations = [
        migrations.CreateModel(
            name='superuser',
            fields=[
                ('userid', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=150)),
                ('dob', models.DateField(null=True)),
                ('registerdate', models.DateTimeField(auto_now=True)),
                ('password', models.CharField(max_length=128)),
            ],
        ),
    ]
