# Generated by Django 3.1.3 on 2024-05-05 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('language', '0011_superuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='superuserlogin',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('time', models.DateTimeField(auto_now=True)),
                ('aspect', models.CharField(default='login', max_length=10)),
            ],
        ),
    ]
